name: Terraform Apply

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform + AWS
        uses: ./.github/actions/setup-terraform
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan